# frozen_string_literal: true
AlgorithmType.find_or_create_by!(id: 1, name: 'measure')
AlgorithmType.find_or_create_by!(id: 2, name: 'flag')
AlgorithmType.find_or_create_by!(id: 3, name: 'analyze')
AlgorithmType.find_or_create_by!(id: 4, name: 'group_measure')
AlgorithmType.find_or_create_by!(id: 5, name: 'gauge')
AlgorithmType.find_or_create_by!(id: 6, name: 'higher_gauge')
AlgorithmType.find_or_create_by!(id: 8, name: 'interact_generic')
AlgorithmType.find_or_create_by!(id: 9, name: 'company_statistic')
AlgorithmType.find_or_create_by!(id: 10, name: 'internal_champion')
AlgorithmType.find_or_create_by!(id: 11, name: 'isolated')
AlgorithmType.find_or_create_by!(id: 12, name: 'connectors')
AlgorithmType.find_or_create_by!(id: 13, name: 'bottlenecks')
AlgorithmType.find_or_create_by!(id: 14, name: 'new_internal_champion')
AlgorithmType.find_or_create_by!(id: 15, name: 'new_connectors')
