EventType.delete_all
EventType.create!(id: 1  , name: 'GENERAL_EVENT') unless EventType.find_by(name: 'GENERAL_EVENT')
EventType.create!(id: 9  , name: 'SCHEDULE_CLIENT_JOB') unless EventType.find_by(name: 'SCHEDULE_CLIENT_JOB')
EventType.create!(id: 10  , name: 'ARCHIVE_OLD_JOBS_QUEUES') unless EventType.find_by(name: 'ARCHIVE_OLD_JOBS_QUEUES')
EventType.create!(id: 11  , name: 'SCHEDULE_JOB') unless EventType.find_by(name: 'SCHEDULE_JOB')
EventType.create!(id: 12  , name: 'ERROR') unless EventType.find_by(name: 'ERROR')
EventType.create!(id: 13  , name: 'FATAL') unless EventType.find_by(name: 'FATAL')
EventType.create!(id: 14  , name: 'WARN') unless EventType.find_by(name: 'WARN')
EventType.create!(id: 15  , name: 'INFO') unless EventType.find_by(name: 'INFO')
EventType.create!(id: 16  , name: 'QUESTIONNAIRE') unless EventType.find_by(name: 'QUESTIONNAIRE')
EventType.create!(id: 17  , name: 'LOGIN') unless EventType.find_by(name: 'LOGIN')
EventType.create!(id: 18  , name: 'COLLECTOR') unless EventType.find_by(name: 'COLLECTOR')
EventType.create!(id: 19  , name: 'JOB_UPDATES') unless EventType.find_by(name: 'JOB_UPDATES')
EventType.create!(id: 20  , name: 'ALERTS_JOB') unless EventType.find_by(name: 'ALERTS_JOB')
EventType.create!(id: 21  , name: 'CREATE_SNAPSHOT_JOB') unless EventType.find_by(name: 'CREATE_SNAPSHOT_JOB')
EventType.create!(id: 22  , name: 'PRECALCULATE_JOB') unless EventType.find_by(name: 'PRECALCULATE_JOB')
